version: "3.9"

services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /volume1/media:/media
      - /volume1/docker/rss-django:/db
    ports:
      - "8100:8100"
  djangoq:
    build: .
    command: python manage.py qcluster
    volumes:
      - .:/code
    ports:
      - "8101:8101"
    depends_on:
      - django
