# Generated by Django 4.0.2 on 2022-02-13 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 2, 13, 15, 17, 40, 716840))),
                ('last_checked', models.DateTimeField()),
                ('save_location', models.FilePathField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('magnet_link', models.URLField()),
                ('uuid', models.UUIDField(unique=True)),
                ('seen', models.DateTimeField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.feed')),
            ],
        ),
    ]
