# Generated by Django 4.0.2 on 2022-02-13 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 15, 25, 16, 930803)),
        ),
        migrations.AlterField(
            model_name='feed',
            name='last_checked',
            field=models.DateTimeField(null=True),
        ),
    ]
