# Generated by Django 4.0.2 on 2022-02-13 20:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_alter_feed_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 20, 30, 45, 540880, tzinfo=utc)),
        ),
    ]
