# Generated by Django 4.0.2 on 2022-02-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_alter_feed_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feeditem',
            name='seen',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
