# Generated by Django 4.0.2 on 2022-02-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0005_alter_feed_created_alter_feeditem_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeditem',
            name='uuid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
