# Generated by Django 4.0.2 on 2022-02-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_alter_feeditem_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='save_location',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
