# Generated by Django 4.0.2 on 2022-02-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0007_alter_feed_save_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='pattern',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='feeditem',
            name='matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='save_location',
            field=models.CharField(max_length=1000, unique=True, verbose_name='Download Path'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True, verbose_name='RSS URL'),
        ),
    ]
