# Generated by Django 4.0.2 on 2022-02-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0008_feed_pattern_feeditem_matched_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='pattern',
            new_name='keyword',
        ),
        migrations.AddField(
            model_name='feeditem',
            name='sent_to_transmission',
            field=models.BooleanField(default=False),
        ),
    ]
